# GitHub actions to enforce Markdown Linting

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint-readme"
   lint-readme:
    name: Lint README.md file
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Lint README.md file
      uses: docker://avtodev/markdown-lint:v1
      with:
        # Fix basic errors
        fix: true  
        args: './README.md'
